# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  port: 5434
  pool: 5

development:
  <<: *default
  database: quora_sinatra
